[package]
name = "hieditor-shellmenu"
version.workspace = true
edition.workspace = true

[lib]
name = "hieditor_shellmenu"
crate-type = ["cdylib", "rlib"]

[target.'cfg(windows)'.dependencies] # 仅 Windows 引入 Win32 依赖，Linux/macOS 下本 crate 编译为空
windows-core = "0.58"
windows = { version = "0.58", features = [
    "implement",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_SystemServices",
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Registry",
] }
